format = "$all"
add_newline = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[\\$](bold green)"

[git_status]
disabled = true

[git_branch]
disabled = true
