#=============================================================================
## dark_powered.toml --- dark powered configuration example for SpaceVim
## Copyright (c) 2016-2017 Wang Shidong & Contributors
## Author: Wang Shidong < wsdjeg at 163.com >
## URL: https://spacevim.org
## License: GPLv3
##=============================================================================
#
## All SpaceVim option below [option] section
[options]
    automatic_update = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "srcery"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    buffer_index_type = 4
    enable_cursorline = true
    enable_statusline_mode = true
    enable_tabline_filetype_icon = true
    enable_tabline_filetype_icon = true
    enable_vimfiler_gitstatus = true
    filemanager = "defx"
    filetree_direction = 'left'
    filetype_icon = true
    relativenumber = false
    statusline_inactive_separator = "nil"
    statusline_separator = "nil"
    vimcompatible = true
    enable_neomake = false
    enable_ale = true
    bootstrap_before = "init#before"
    bootstrap_after = "init#after"
    project_rooter_automatically = 0

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
  rust = ["rls"]

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "checkers"

[[layers]]
  name = "japanese"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "ui"
  enable = true
  enable_sidebar = true

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "github"

[[layers]]
  name = "fzf"

[[layers]]
  name = "tools"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#rust"
  format-autosave = true

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lang#php"

[[custom_plugins]]
  name = "jceb/vim-orgmode"
  merged = 0
